name: Build Desktop App

on:
  push:
    branches: [ main, editor-yoopta, audio-improvements-robust ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Build application
        run: npm run make
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: writegeist-desktop-installer
          path: |
            out/make/squirrel.windows/x64/*.exe
            out/make/squirrel.windows/x64/RELEASES
          retention-days: 30
          
      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "out/make/squirrel.windows/x64/*.exe"
          draft: false
          prerelease: false
          allowUpdates: true
          updateOnlyUnreleased: false
          token: ${{ secrets.GITHUB_TOKEN }} 